spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskforge
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: taskforge

server:
  port: 8080
